{{- if .Values.postgres.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "concierge.fullname" . }}-db
  labels:
    app.kubernetes.io/name: {{ include "concierge.name" . }}-postgres
    helm.sh/chart: {{ include "concierge.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgres
      protocol: TCP
      name: postgres
  selector:
    app.kubernetes.io/name: {{ include "concierge.name" . }}-postgres
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}